### ISSUE TITLE
project related object

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1704]
If the clients sends a request to the server to project an agenda item, the server should not save the item in the database but the related item.

**Comment by normanjaeckel** [comment]
Hm. At the moment this is fixed by just not sending `agenda/item` to the projector. Do you want me to change the server side because you later want to change the clients behavior?

**Comment by normanjaeckel** [comment]
@emanuelschuetze may also answer this.

**Comment by emanuelschuetze** [comment]
I'm not sure what the plan of this issue was. I tesed successfully a quick fix of @ostcar, but he means this need server side adaptions:
https://github.com/OpenSlides/OpenSlides/compare/master...emanuelschuetze:project-item-fix?expand=1

**Comment by ostcar** [comment]
The commit did not fix this issue.

To project an agenda item, we fetch the related item from the server: https://github.com/OpenSlides/OpenSlides/blob/master/openslides/agenda/static/js/agenda/site.js#L89

This is not necessary. The client should send the agenda item to the server and the server should save the corresponding object into the db.

This is not only faster, but it is also easier for other clients that work with our rest-api. Something meaningful should happen, when the client sends item-5 to the projector. At the moment this does not throws an error but activates a diffrent slide, then when activating the corresponding. related_object.

**Comment by normanjaeckel** [comment]
This is not that easy as it looks like:

# Option 1
We do nothing and close this issue. Advantage: Nothing to do on server side (I just can delete some unused lines in agenda/projector.py – no problem.). No disadvantages as shown below. Disadvantage: On client side the related object has to be fetched before the projector button in the agenda can be displayed because this button has to be modified to activate the related slide not the item slide. The question is whether this is a big disadvantage or not.

# Option 2
We change the request so that if someone tries to activate `{"name": "agenda/item", "id": "5"}` we save something like `{"name": "motions/motion", "id": "42"}` into the database. Advantage: After successful save we have to do nothing more. Server and client behave as if someone would have clicked the other projector button. Disadvantage: The whole projector viewset has to be split up. At the moment I just validate dictionaries and do not check or manipulate the content further on. So I can use smart code from the Django REST framework serializer API. With this option I have to add agenda specific code to the core app to check if someone sends `"agenda/item"` and the implement this logic (fetch the item from the database, fetch the related object, get the slide name and id, change the request value before it is saved into the database).

# Option 3
I just change the output of the projector serializer. That means in the database we find `{"name": "agenda/item", "id": "5"}` but if you make a GET request on the projector he tells you that `{"name": "motions/motion", "id": "42"}` is active. Advantage: The client has nothing to do, like in option 2 but without the disadvantage of option 2. Disadvantage: This is hidden magic. A client analyzing the REST requests and answers could be confused because the projector answers sometimes like this, sometimes like that. Also we have to do massive changes in the ProjectorRequirements API which are resposible for proper permission handling at the moment.

I prefer option 1. What do you think?

**Comment by ostcar** [comment]
I am in favour of Option 2.

I think the server should filter the input of the client in general. If someone does not use the angular-client but send manual requests to our rest api, then no strange behaviour should happen. This apply to any post request. A "form" where we check for required fields of the right type of a field, as well as the projector.

If it is invalid to send agenda/item as active element, then the server should reject it or "fix" it. If it is nor invalid, then we have to make a clear decision what should happen, if the client sends it, even if the angular client does never do it.

**Comment by normanjaeckel** [comment]
> I think the server should filter the input of the client in general. If someone does not use the angular-client but send manual requests to our rest api, then no strange behaviour should happen. This apply to any post request. A "form" where we check for required fields of the right type of a field, as well as the projector.

If we set sending "agenda/item" as invalid (this would be no problem, see sentence in brackets in option 1) then I prefer that the server does not fix it by changing the request value because this would be a hidden feature and the client developer may be confused what happens to his data. So this is an argument for option 1 not for option 2.

**Comment by emanuelschuetze** [comment]
as discussed, we choose option 1 with modification. I'll make a pull request to override project()...
